"""Add location, max_capacity, operating_hours fields

Revision ID: 888575a67cab
Revises: 
Create Date: 2026-01-31 18:35:52.541310

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '888575a67cab'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('spaces', schema=None) as batch_op:
        batch_op.add_column(sa.Column('location', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('max_capacity', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('operating_hours', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('spaces', schema=None) as batch_op:
        batch_op.drop_column('operating_hours')
        batch_op.drop_column('max_capacity')
        batch_op.drop_column('location')

    # ### end Alembic commands ###
